"""Fetch/prepare + deploy-plan construction for the miner self-deploy flow.

This module turns the miner's inputs (a digest-pinned canonical image reference, a
validator key-release endpoint URL, an optional CPU shape) into:

* a :class:`PreparedDeployment` — the generated, deterministic Phala
  ``app-compose`` (referencing the exact image digest, mounting the dstack +
  guest Docker sockets, and carrying the validator key-release endpoint) plus its
  reproducible compose-hash (VAL-DEPLOY-002); and
* a :class:`DeployPlan` — the prepared deployment plus the validated CPU shape,
  region, projected cost, and the ``encrypted_env`` name set, ready to hand to a
  deployer or print as a no-spend dry-run (VAL-DEPLOY-008/009).

All guards are pure and run BEFORE any provisioning: GPU targets and over-cap
shapes are refused with zero Phala calls (:mod:`.shapes`), and missing Phala
credentials error clearly (:func:`check_phala_credentials`) without ever printing
the key value (VAL-DEPLOY-006/007/008).
"""

from __future__ import annotations

import os
from collections.abc import Mapping
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from agent_challenge.canonical.compose import (
    DEFAULT_ALLOWED_ENVS,
    DEFAULT_APP_NAME,
    ComposeGenerationError,
    app_compose_hash,
    assert_digest_pinned,
    generate_app_compose,
    render_app_compose,
    write_app_compose,
)
from agent_challenge.canonical.live_registry import (
    LiveRegistryError,
    load_live_registry,
)
from agent_challenge.keyrelease.client import KEY_RELEASE_URL_ENV
from agent_challenge.selfdeploy.shapes import (
    DEFAULT_MAX_RUNTIME_HOURS,
    DEFAULT_MONEY_CAP_USD,
    DEFAULT_OS_IMAGE,
    CpuShape,
    select_default_instance_type,
    validate_cpu_only,
    validate_within_cap,
)

#: Environment variable holding the Phala Cloud API key (AGENTS.md). Never printed.
PHALA_API_KEY_ENV = "PHALA_CLOUD_API_KEY"

#: Default Phala region for CPU Intel TDX.
#: Live teepod capacity is under ``us-west-1``; bare ``us-west`` fails with
#: ERR-02-002 (No teepod found). See selfdeploy.phala.normalize_phala_region.
DEFAULT_REGION = "us-west-1"

#: Filename of the deployable app-compose written by ``prepare``.
APP_COMPOSE_FILENAME = "app-compose.json"


class PrepareError(ValueError):
    """The fetch/prepare inputs are invalid (bad image ref / missing endpoint)."""


class CredentialError(RuntimeError):
    """Phala credentials are missing/unusable (deploy refuses, no CVM call)."""


@dataclass(frozen=True)
class PreparedDeployment:
    """The generated compose + reproducible hash for a canonical-image deployment."""

    image: str
    key_release_url: str
    compose: dict[str, Any]
    compose_text: str
    compose_hash: str
    allowed_envs: tuple[str, ...]

    def orchestrator_environment(self) -> list[str]:
        """The orchestrator service ``environment`` entries in the generated compose."""

        services = self.compose.get("docker_compose_file", "")
        # The compose is generated by canonical.compose; parse the embedded YAML.
        import yaml

        parsed = yaml.safe_load(services) if isinstance(services, str) else {}
        service = (parsed or {}).get("services", {}).get("orchestrator", {})
        env = service.get("environment", [])
        return [str(entry) for entry in env]


@dataclass(frozen=True)
class DeployPlan:
    """A fully-validated, no-spend deploy plan (safe to print as a dry-run)."""

    prepared: PreparedDeployment
    instance_type: str
    os_image: str
    region: str
    shape: CpuShape
    projected_cost_usd: float
    money_cap_usd: float
    max_runtime_hours: float
    name: str
    encrypted_env: dict[str, str] = field(default_factory=dict)

    @property
    def image(self) -> str:
        return self.prepared.image

    @property
    def key_release_url(self) -> str:
        return self.prepared.key_release_url

    @property
    def compose_hash(self) -> str:
        return self.prepared.compose_hash


def resolve_orchestrator_image(
    *,
    image: str | None = None,
    live_registry_path: Path | str | None = None,
) -> str:
    """Resolve the pullable, digest-pinned orchestrator image the deploy pins.

    Prefers an explicit ``image``; otherwise reads the recorded
    ``orchestrator_image`` from the live-registry side manifest. Raises
    :class:`PrepareError` when neither is available so the deploy never silently
    falls back to an unpinned/absent image.
    """

    if isinstance(image, str) and image.strip():
        return image.strip()
    if live_registry_path is not None:
        try:
            registry = load_live_registry(live_registry_path)
        except LiveRegistryError as exc:
            raise PrepareError(str(exc)) from exc
        if registry.orchestrator_image:
            return registry.orchestrator_image
    raise PrepareError(
        "no orchestrator image given and none recorded in the live-registry manifest; "
        "pass an explicit digest-pinned image or a manifest that records orchestrator_image"
    )


def prepare_deployment(
    *,
    image: str,
    key_release_url: str,
    app_name: str = DEFAULT_APP_NAME,
    allowed_envs: tuple[str, ...] = DEFAULT_ALLOWED_ENVS,
    live_registry_manifest_path: str | None = None,
) -> PreparedDeployment:
    """Resolve the canonical image to a digest-pin and generate the compose.

    Fails closed on a floating (non-digest) image tag or a missing key-release
    endpoint so a miner can never deploy an unpinned image or a run with no
    validator endpoint (VAL-DEPLOY-002).

    When ``live_registry_manifest_path`` is given the generated compose points the
    in-CVM DooD orchestrator at the live-registry side manifest (for the live
    task-image subset); with none supplied the compose is byte-identical to the
    offline/flag-off default.
    """

    if not isinstance(key_release_url, str) or not key_release_url.strip():
        raise PrepareError(
            "a validator key-release endpoint URL is required (the run cannot obtain the "
            "golden key without it)"
        )
    endpoint = key_release_url.strip()
    try:
        pinned = assert_digest_pinned(image, what="canonical image")
    except ComposeGenerationError as exc:
        raise PrepareError(str(exc)) from exc

    compose = generate_app_compose(
        orchestrator_image=pinned,
        name=app_name,
        key_release_url=endpoint,
        allowed_envs=allowed_envs,
        live_registry_manifest_path=live_registry_manifest_path,
    )
    return PreparedDeployment(
        image=pinned,
        key_release_url=endpoint,
        compose=compose,
        compose_text=render_app_compose(compose),
        compose_hash=app_compose_hash(compose),
        allowed_envs=tuple(compose["allowed_envs"]),
    )


def write_prepared(prepared: PreparedDeployment, out_dir: Path | str) -> Path:
    """Write the deployable ``app-compose.json`` (exact bytes) into ``out_dir``.

    The bytes written are ``canonical.compose.render_app_compose`` verbatim, so
    the on-disk file hashes to :attr:`PreparedDeployment.compose_hash` (and hence
    the live CVM ``compose_hash`` / RTMR3 event).
    """

    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    path = out / APP_COMPOSE_FILENAME
    write_app_compose(path, prepared.compose)
    return path


def check_phala_credentials(env: Mapping[str, str] | None = None) -> None:
    """Require a non-empty Phala API key; raise clearly WITHOUT echoing it.

    Raises :class:`CredentialError` naming the missing credential when
    :data:`PHALA_API_KEY_ENV` is unset/empty. The key VALUE is never included in
    the message, returned, or logged (VAL-DEPLOY-006).
    """

    source = env if env is not None else os.environ
    key = (source.get(PHALA_API_KEY_ENV) or "").strip()
    if not key:
        raise CredentialError(
            f"{PHALA_API_KEY_ENV} is not set; export your Phala Cloud API key before deploying. "
            "The key value is never printed."
        )


def build_deploy_plan(
    *,
    image: str,
    key_release_url: str,
    instance_type: str | None = None,
    os_image: str = DEFAULT_OS_IMAGE,
    region: str = DEFAULT_REGION,
    money_cap_usd: float = DEFAULT_MONEY_CAP_USD,
    max_runtime_hours: float = DEFAULT_MAX_RUNTIME_HOURS,
    name: str = DEFAULT_APP_NAME,
    encrypted_env: Mapping[str, str] | None = None,
    live_registry_manifest_path: str | None = None,
) -> DeployPlan:
    """Build a validated, no-spend deploy plan (all guards run, no Phala call).

    Resolves the default smallest CPU shape when none is given, refuses GPU
    targets and over-cap shapes, and prepares the compose. Raises
    :class:`~agent_challenge.selfdeploy.shapes.ShapeError` (GPU / unknown / over
    cap) before any provisioning; credential checking is a separate, later step so
    a GPU/over-cap refusal never needs credentials (VAL-DEPLOY-007/008).

    When ``live_registry_manifest_path`` is given the generated compose points the
    in-CVM DooD orchestrator at the live-registry side manifest (live task-image
    subset); with none supplied the compose is byte-identical to the offline
    default.
    """

    # Local import: phala imports CredentialError from this module (cycle-safe).
    from agent_challenge.selfdeploy.phala import normalize_phala_region

    resolved_type = (instance_type or "").strip() or select_default_instance_type()
    shape = validate_cpu_only(instance_type=resolved_type, os_image=os_image)
    cost = validate_within_cap(
        resolved_type,
        money_cap_usd=money_cap_usd,
        max_runtime_hours=max_runtime_hours,
    )
    deployment_env = dict(encrypted_env or {})
    if "EVAL_RUN_TOKEN" in deployment_env and set(deployment_env) != {"EVAL_RUN_TOKEN"}:
        raise PrepareError("Eval deploy encrypted_env must contain only EVAL_RUN_TOKEN")
    prepared = prepare_deployment(
        image=image,
        key_release_url=key_release_url,
        app_name=name,
        live_registry_manifest_path=live_registry_manifest_path,
    )

    env: dict[str, str] = {KEY_RELEASE_URL_ENV: prepared.key_release_url}
    env.update({str(k): str(v) for k, v in deployment_env.items()})

    # Remap bare us-west → us-west-1 so DEFAULT_REGION never hard-fails capacity.
    resolved_region = normalize_phala_region(region) or DEFAULT_REGION

    return DeployPlan(
        prepared=prepared,
        instance_type=resolved_type,
        os_image=os_image,
        region=resolved_region,
        shape=shape,
        projected_cost_usd=cost,
        money_cap_usd=money_cap_usd,
        max_runtime_hours=max_runtime_hours,
        name=name,
        encrypted_env=env,
    )


def render_plan(plan: DeployPlan) -> dict[str, Any]:
    """The full dry-run plan as a JSON-serializable dict (no secret values).

    Surfaces every field a miner needs to review before spending: the exact
    compose text + hash, the image digest, instance type, region, OS image, the
    validator key-release endpoint, and the projected cost. Only the
    ``encrypted_env`` NAMES are shown (never values), so printing the plan leaks
    no secret (VAL-DEPLOY-009).
    """

    return {
        "image": plan.image,
        "instance_type": plan.instance_type,
        "os_image": plan.os_image,
        "region": plan.region,
        "key_release_url": plan.key_release_url,
        "compose_hash": plan.compose_hash,
        "compose": plan.prepared.compose_text,
        "projected_cost_usd": round(plan.projected_cost_usd, 4),
        "money_cap_usd": plan.money_cap_usd,
        "max_runtime_hours": plan.max_runtime_hours,
        "name": plan.name,
        "encrypted_env_names": sorted(plan.encrypted_env),
        "dry_run": True,
    }


__all__ = [
    "APP_COMPOSE_FILENAME",
    "DEFAULT_REGION",
    "PHALA_API_KEY_ENV",
    "CredentialError",
    "DeployPlan",
    "PrepareError",
    "PreparedDeployment",
    "build_deploy_plan",
    "check_phala_credentials",
    "prepare_deployment",
    "render_plan",
    "resolve_orchestrator_image",
    "write_prepared",
]
