"""Canonical, versioned Base challenge SDK public surface."""

from .api_manifest import API_MANIFEST, API_MANIFEST_DIGEST, ApiManifest
from .app_factory import ChallengeDatabase, create_challenge_app
from .auth import build_internal_auth_dependency, load_shared_token
from .compatibility import SemVer, is_compatible, require_compatible
from .config import ChallengeSettings, DockerExecutorSettings
from .executors.docker import (
    DockerContainerInfo,
    DockerExecutor,
    DockerExecutorError,
    DockerLimits,
    DockerMount,
    DockerRunResult,
    DockerRunSpec,
)
from .roles import (
    CAPABILITY_REGISTRY_VERSION,
    ROLE_REGISTRY,
    Capability,
    CapabilityRegistry,
    CapabilitySpec,
    Role,
    RoleContext,
    RoleContractError,
    activate_role,
    capabilities_for_role,
    challenge_only,
    current_role,
    is_public_route,
    master_only,
    public_route,
    role_contract,
    validator_only,
    worker_only,
)
from .schemas import (
    AssignmentProgressRequest,
    AssignmentProgressResponse,
    AssignmentPullResponse,
    AssignmentResultRequest,
    AssignmentResultResponse,
    AssignmentView,
    EmptyObject,
    ErrorResponse,
    ExternalResultEnvelope,
    ExternalResultResponse,
    HealthResponse,
    RawWeightPushAcknowledgement,
    RawWeightPushRequest,
    ValidatorHeartbeatRequest,
    ValidatorHeartbeatResponse,
    ValidatorRegisterRequest,
    ValidatorRegisterResponse,
    ValidatorView,
    VersionResponse,
    WeightsResponse,
    WorkUnitFoldRequest,
)
from .version import (
    API_VERSION,
    ARTIFACT_VERSION,
    DISTRIBUTION_NAME,
    RELEASE_ID,
    RELEASE_MANIFEST,
    SDK_CONTRACT_VERSION,
)

__all__ = [
    "API_VERSION",
    "API_MANIFEST",
    "API_MANIFEST_DIGEST",
    "ARTIFACT_VERSION",
    "ApiManifest",
    "AssignmentProgressRequest",
    "AssignmentProgressResponse",
    "AssignmentPullResponse",
    "AssignmentResultRequest",
    "AssignmentResultResponse",
    "AssignmentView",
    "EmptyObject",
    "CAPABILITY_REGISTRY_VERSION",
    "Capability",
    "CapabilityRegistry",
    "CapabilitySpec",
    "ErrorResponse",
    "ExternalResultEnvelope",
    "ExternalResultResponse",
    "ROLE_REGISTRY",
    "Role",
    "RoleContext",
    "RoleContractError",
    "RawWeightPushAcknowledgement",
    "RawWeightPushRequest",
    "ChallengeDatabase",
    "ChallengeSettings",
    "SemVer",
    "DISTRIBUTION_NAME",
    "DockerContainerInfo",
    "DockerExecutor",
    "DockerExecutorError",
    "DockerExecutorSettings",
    "DockerLimits",
    "DockerMount",
    "DockerRunResult",
    "DockerRunSpec",
    "HealthResponse",
    "RELEASE_ID",
    "RELEASE_MANIFEST",
    "SDK_CONTRACT_VERSION",
    "VersionResponse",
    "ValidatorHeartbeatRequest",
    "ValidatorHeartbeatResponse",
    "ValidatorRegisterRequest",
    "ValidatorRegisterResponse",
    "ValidatorView",
    "WeightsResponse",
    "WorkUnitFoldRequest",
    "build_internal_auth_dependency",
    "is_compatible",
    "require_compatible",
    "activate_role",
    "capabilities_for_role",
    "challenge_only",
    "create_challenge_app",
    "current_role",
    "is_public_route",
    "master_only",
    "load_shared_token",
    "public_route",
    "role_contract",
    "validator_only",
    "worker_only",
]
