"""Canonical baseagent skeleton fingerprint used to subtract shared base code.

Every miner forks the same ``baseagent`` skeleton (``agent.py`` + ``src/**``), so
raw AST similarity between two forks is dominated by that shared boilerplate. The
fingerprint here is the set of ``ast_hash`` (rename/format-invariant) and raw
``file_hash`` values of the baseagent skeleton, generated by
``scripts/gen_baseagent_skeleton_hashes.py`` and shipped alongside this module at
``baseagent-skeleton-hashes.json`` (inside the ``agent_challenge.analyzer``
package, so it is present in every image/install). Similarity scoring subtracts
any file whose fingerprint is in this set so only each submission's DELTA is
scored.

Loading is resilient: if the manifest is missing or unreadable the fingerprint is
empty and no subtraction happens (behavior identical to before this feature).
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

from agent_challenge.core.config import settings

logger = logging.getLogger(__name__)

#: Packaged default: the manifest ships next to this module inside the
#: ``agent_challenge.analyzer`` package, so it is present in every image/install
#: (the package tree is always on ``PYTHONPATH``).
_DEFAULT_MANIFEST_PATH = Path(__file__).resolve().parent / "baseagent-skeleton-hashes.json"


@dataclass(frozen=True)
class BaseSkeletonFingerprint:
    ast_hashes: frozenset[str]
    file_hashes: frozenset[str]

    def __bool__(self) -> bool:
        return bool(self.ast_hashes or self.file_hashes)


_EMPTY = BaseSkeletonFingerprint(ast_hashes=frozenset(), file_hashes=frozenset())
_cache: BaseSkeletonFingerprint | None = None


def _manifest_path() -> Path:
    configured = settings.analyzer_base_skeleton_manifest
    return Path(configured) if configured else _DEFAULT_MANIFEST_PATH


def load_base_skeleton_fingerprint(path: str | Path | None = None) -> BaseSkeletonFingerprint:
    manifest_path = Path(path) if path is not None else _manifest_path()
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        logger.warning("baseagent skeleton manifest unavailable at %s: %s", manifest_path, exc)
        return _EMPTY
    if not isinstance(data, dict):
        logger.warning("baseagent skeleton manifest at %s is malformed", manifest_path)
        return _EMPTY
    return BaseSkeletonFingerprint(
        ast_hashes=_string_set(data.get("ast_hashes")),
        file_hashes=_string_set(data.get("file_hashes")),
    )


def base_skeleton_fingerprint() -> BaseSkeletonFingerprint:
    global _cache
    if _cache is None:
        _cache = load_base_skeleton_fingerprint()
    return _cache


def reset_base_skeleton_cache() -> None:
    global _cache
    _cache = None


def _string_set(value: object) -> frozenset[str]:
    if not isinstance(value, list):
        return frozenset()
    return frozenset(str(item) for item in value if item)
