"""Master LLM gateway: provider abstraction, scoped tokens, forward routes."""

from base.master.llm_gateway.gateway import (
    DEEPSEEK_BASE_URL_ENV,
    DEEPSEEK_PROVIDER,
    DEEPSEEK_REQUIRED_MODEL,
    GATEWAY_ASSIGNMENT_HEADER,
    GATEWAY_TOKEN_ENV,
    GATEWAY_TOKEN_HEADER,
    GATEWAY_VALIDATOR_HEADER,
    OPENROUTER_PROVIDER,
    AuthenticatedCall,
    GatewayError,
    LLMGatewayService,
    ModelNotAllowedError,
    UnknownProviderError,
    build_llm_gateway_router,
    build_llm_gateway_service,
)
from base.master.llm_gateway.providers import (
    DEEPSEEK_BASE_URL,
    OPENROUTER_BASE_URL,
    HttpLLMProvider,
    LLMProvider,
    MockLLMProvider,
    ProviderConfig,
    ProviderRequest,
    ProviderResponse,
    RecordedProviderRequest,
    build_providers,
    compose_provider_url,
)
from base.master.llm_gateway.tokens import (
    GatewayTokenAuthority,
    GatewayTokenClaims,
    GatewayTokenError,
    GatewayTokenExpired,
    GatewayTokenInvalid,
    GatewayTokenScopeError,
)

__all__ = [
    "DEEPSEEK_BASE_URL",
    "DEEPSEEK_BASE_URL_ENV",
    "DEEPSEEK_PROVIDER",
    "DEEPSEEK_REQUIRED_MODEL",
    "GATEWAY_ASSIGNMENT_HEADER",
    "GATEWAY_TOKEN_ENV",
    "GATEWAY_TOKEN_HEADER",
    "GATEWAY_VALIDATOR_HEADER",
    "OPENROUTER_BASE_URL",
    "OPENROUTER_PROVIDER",
    "AuthenticatedCall",
    "GatewayError",
    "GatewayTokenAuthority",
    "GatewayTokenClaims",
    "GatewayTokenError",
    "GatewayTokenExpired",
    "GatewayTokenInvalid",
    "GatewayTokenScopeError",
    "HttpLLMProvider",
    "LLMGatewayService",
    "LLMProvider",
    "MockLLMProvider",
    "ModelNotAllowedError",
    "ProviderConfig",
    "ProviderRequest",
    "ProviderResponse",
    "RecordedProviderRequest",
    "UnknownProviderError",
    "build_llm_gateway_router",
    "build_llm_gateway_service",
    "build_providers",
    "compose_provider_url",
]
